### PR TITLE
replace validate_* calls with puppet4 datatypes

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by xaque208** [comment]
@bastelfreak I'm going to get #14 ahead of this one to help out on the testing side.

**Comment by xaque208** [comment]
I created a conflict here, my apologies.  Would you mind a rebase here please?

**Comment by bastelfreak** [comment]
@xaque208 all fixed

**Comment by xaque208** [comment]
Merged out of band.  Thanks @bastelfreak!

**Pull request merged**
